name: Deploy to GitHub pages
on:
  push:
    branches: [ main ]
env:
  BUILD_FOLDER: .output/public
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate static Nuxt 3 files
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: 'yarn'

      - run: |
          yarn install
          yarn generate

      - name: Add .nojekyll to running folder
        run: |
          cd $BUILD_FOLDER
          touch .nojekyll

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{env.BUILD_FOLDER}}